name: Create PR with String Replacement
run-name: Create PR with String Replacement by @${{ github.actor }}
on:
  pull_request: ## TODO: delete
  workflow_dispatch:
    inputs:
      search_string:
        description: 'Search String to Replace'
        required: true
        default: 'TYPO'
      replace_string:
        description: 'Replace String'
        required: true
        default: 'TT'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate branch name
        id: branchname
        run: echo "MY_BRANCH=feature/replace-strings-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT            
      - name: Check out code
        uses: actions/checkout@v4
      - name: Replace strings
        run: sed -i "s/${{ github.event.inputs.search_string }}/${{ github.event.inputs.replace_string }}/g" ./README.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Replace '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          branch: ${{ steps.branchname.outputs.MY_BRANCH }}
          base: main
          title: Replace '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          body: This PR replaces '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          labels: 'automated pr'
