name: Create PR with IP Address Replacement
run-name: Create PR with IP Address Replacement by @${{ github.actor }}
on:
  push: ## TODO: delete
  workflow_dispatch:
    inputs:
      search_ip:
        description: 'Search IP Address to Replace'
        required: true
        default: '1.2.3.4'
      replace_ip:
        description: 'Replace IP Address'
        required: true
        default: '5.6.7.8'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      # 上記に加えてリポジトリ設定(https://github.com/YOUR_ORG/YOUR_REPO/settings/actions) にて
      # PR作成権限 (`Allow GitHub Actions to create and approve pull requests`) のチェックONが必要
      # https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
      # https://stackoverflow.com/questions/72376229/github-actions-is-not-permitted-to-create-or-approve-pull-requests-createpullre
    env:
      SEARCH:  ${{ github.event.inputs.search_ip || '1.2.3.4' }}
      REPLACE: ${{ github.event.inputs.replace_ip || '5.6.7.8' }}
    steps:
      - name: Generate branch name
        id: branchname
        run: echo "MY_BRANCH=feature/replace-strings-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT            
      - name: Get pull request template
        id: pr_tmpl
        run: echo "MY_PR_TMPL=$(cat ./.github/PULL_REQUEST_TEMPLATE.md)" >> $GITHUB_OUTPUT            
      - name: Check out code
        uses: actions/checkout@v4
      - name: Replace strings
        run: sed -i "s@${{ env.SEARCH }}@${{ env.REPLACE }}@g" ./README.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Replace "${{ env.SEARCH }}" with "${{ env.REPLACE }}"
          branch: ${{ steps.branchname.outputs.MY_BRANCH }}
          base: main
          title: Replace "${{ env.SEARCH }}" with "${{ env.REPLACE }}" by @${{ github.actor }}
          body: ${{ steps.pr_tmpl.outputs.MY_PR_TMPL }}
          labels: 'automated pr'
