name: Create PR with String Replacement

on:
  workflow_dispatch:
    inputs:
      search_string:
        description: 'Search String to Replace'
        required: true
      replace_string:
        description: 'Replace String'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRET }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: Generate Branch Name
        id: branchname
        run: echo "::set-output name=MY_BRANCH::feature/replace-strings-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Check out code
        uses: actions/checkout@v4

      - name: Replace Strings
        run: |
          find . -type f -name '*' -exec sed -i "s/${{ github.event.inputs.search_string }}/${{ github.event.inputs.replace_string }}/g" {} \;

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: |
            Replace '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          branch: ${{ steps.branchname.outputs.MY_BRANCH }}
          base: main
          title: |
            Replace '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          body: |
            This PR replaces '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          labels: 'automated pr'
