name: Create PR with String Replacement
run-name: Create PR with String Replacement by @${{ github.actor }}
on:
  pull_request: ## TODO: delete
  workflow_dispatch:
    inputs:
      search_string:
        description: 'Search String to Replace'
        required: true
        default: '1.2.3.4'
      replace_string:
        description: 'Replace String'
        required: true
        default: '5.6.7.8'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      # 上記に加えてリポジトリ設定(https://github.com/YOUR_ORG/YOUR_REPO/settings/actions) にて
      # PR作成権限 (`Allow GitHub Actions to create and approve pull requests`) のチェックONが必要
      # https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
      # https://stackoverflow.com/questions/72376229/github-actions-is-not-permitted-to-create-or-approve-pull-requests-createpullre
    steps:
      - name: Generate branch name
        id: branchname
        run: echo "MY_BRANCH=feature/replace-strings-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT            
      - name: Check out code
        uses: actions/checkout@v4
      - name: Replace strings
        run: sed -i "s@${{ github.event.inputs.search_string }}@${{ github.event.inputs.replace_string }}@g" ./README.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Replace '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          branch: ${{ steps.branchname.outputs.MY_BRANCH }}
          base: main
          title: Replace '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          body: This PR replaces '${{ github.event.inputs.search_string }}' with '${{ github.event.inputs.replace_string }}'
          labels: 'automated pr'
